# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\timetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(4095, 1080)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(100, 120, 1664, 833))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1664, 833))
        self.tableWidget.setDisabled(True)
        self.tableWidget.setObjectName("tableWidget")
        col = 7
        row =10
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        for i in range(0,row):
            self.tableWidget.setVerticalHeaderItem(i, item)
        for i in range(0,col):
            self.tableWidget.setHorizontalHeaderItem(i, item)
        
    
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 0, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)

        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.verticalHeader().setDefaultSectionSize(80)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "09:30"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "10:30"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "11:30"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "12:30"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "13:30"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "14:30"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "15:30"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "16:30"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "17:30"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "18:30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sun"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Mon"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tue"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Wed"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Thu"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fri"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Sat"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
