# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\course_material.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

from course_info import CourseInfo


class Course_Item:
        
    def __init__(self, scrollAreaWidgetContents, data, h,MainWindow):
      def toCourse_Info(MainWindow, course_id):
        item = MainWindow.gridLayout.takeAt(2)
        if item is not None:
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
        uiCourseMaterial = CourseInfo()
        uiCourseMaterial.setupUi(MainWindow,course_id)

      self = QtWidgets.QWidget(scrollAreaWidgetContents)
      _translate = QtCore.QCoreApplication.translate
      self.setGeometry(QtCore.QRect(0, h, 1661, 101))
      self.setObjectName("widget")
      label = QtWidgets.QPushButton(self)
      label.setGeometry(QtCore.QRect(100, 20, 1501, 61))
      font = QtGui.QFont()
      font.setPointSize(24)
      font.setBold(True)
      font.setWeight(75)
      label.setFont(font)
      label.setObjectName(data[0])
      label.setStyleSheet("border: none; text-align:left ")  
      label.setText(_translate("Form", data[0]+" "+data[1]))
      if MainWindow != False:
        label.clicked.connect(lambda:toCourse_Info(MainWindow,data[2]))

class Course_List(object):
    def setupUi(self, MainWindow):
    # base on ClassTaken and Courses, from sql
        self.sqlSem1CourseData = [("COMP3278","Course Name","course_id"),
                         ("COMP3278","Course Name","course_id"),
                         ("COMP3278","Course Name","course_id"),
                         ("COMP3278","Course Name","course_id"),
                         ("COMP3278","Course Name","course_id")]
        self.sqlSem2CourseData = [("COMP3297","Course Name","course_id"),
                         ("COMP3297","Course Name","course_id"),
                         ("COMP3297","Course Name","course_id"),
                         ("COMP3297","Course Name","course_id"),
                         ("COMP32976","Course Name","course_id")]
    #not from sql, manually do it
        self.sqlCourseData = [self.sqlSem1CourseData,self.sqlSem2CourseData]
        self.frame = QtWidgets.QFrame()
        self.frame.setFixedHeight(833)
        self.frame.setFixedWidth(1664)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: 0px")

        font = QtGui.QFont()
        font.setPointSize(24)
        self.Title = QtWidgets.QLabel(self.frame)
        self.Title.setGeometry(QtCore.QRect(0, 0, 1664, 110))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 110, 1661, 521))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.horizontalScrollBar().setStyleSheet("QScrollBar {height:0px;}")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1659, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        
        self.courseItem = []
        h= 0
        for sem in range(0,2):
          self.courseItem.append(Course_Item(self.scrollAreaWidgetContents,("Semester", str(sem+1)), h,False))
          h+=130
          for i in self.sqlCourseData[sem]:
            self.courseItem.append(Course_Item(self.scrollAreaWidgetContents,i, h,MainWindow))
            h+=130

        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, len(self.courseItem)*130))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.gridLayout.addWidget(self.frame,2,1,1,1)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Title.setText(_translate("Form", "Course List"))
      
