# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\course_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

from course_material import Material_List
#from sql
#give the nearest one if there are more than one class
class CourseInfo(object):
    def setupUi(self, MainWindow, course_id):
        #using course_id to fetch data
        self.sqlCourseData = [("COMP3278", "Introduction to Database Management Systems", "[teacher’s message]", "classroom address",
        datetime.time(15,30,00,00),"[links of Zoom]")]
        self.sqlMaterialData = [("Lecture 1 note"),("Lecture 2 note"),("Lecture 3 note")]
        # end of fetching, start gui construction
        self.sqlCourseData = self.sqlCourseData[0]
        self.frame = QtWidgets.QFrame()
        self.frame.setFixedHeight(833)
        self.frame.setFixedWidth(1664)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 1664, 200))
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 200, 832, 384))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_3.setGeometry(QtCore.QRect(832, 200, 832, 384))
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(1269, 684, 395, 73))
        
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda:self.toMaterial(MainWindow,course_id))
        MainWindow.gridLayout.addWidget(self.frame,2,1,1,1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, Form):
        time = self.sqlCourseData[4].strftime("%H:%M:%S")
        materialList = ""
        for i in self.sqlMaterialData:
            materialList = materialList+i+"<br />"
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\" font-family:\'Inter\'; font-size:64px; font-weight:696; color:#000000; vertical-align:middle;\">"
""+self.sqlCourseData[0]+"<br />"+self.sqlCourseData[1]+"<br /></span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form","<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\"font-family:\'Inter\'; font-size:28px; font-weight:696; color:#000000;\">"
""+self.sqlCourseData[2]+"<br />"+self.sqlCourseData[3]+"<br />"+time+"<br />"+self.sqlCourseData[5]+"<br /></span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\"font-family:\'Inter\'; font-size:28px; font-weight:696; color:#000000;\">"
""+materialList+"</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Get Material"))
    
    def toMaterial(self,MainWindow,course_id):
        item = MainWindow.gridLayout.takeAt(2)
        if item is not None:
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
        uiCourseMaterial = Material_List()
        uiCourseMaterial.setupUi(MainWindow,course_id)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = CourseInfo()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
