# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\course_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
#from sql
sqlCourseData = [("COMP3278", "Introduction to Database Management Systems", "[teacher’s message]", "classroom address",
datetime.time(15,30,00,00),"[links of Zoom]")]
sqlMaterialData = [("Lecture 1 note"),("Lecture 2 note"),("Lecture 3 note")]

sqlCourseData = sqlCourseData[0]
class CourseInfo(object):
    def setupUi(self, Form):

        self.frame = QtWidgets.QFrame()
        self.frame.setFixedHeight(757)
        self.frame.setFixedWidth(1664)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 1664, 200))
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 200, 832, 384))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_3.setGeometry(QtCore.QRect(832, 200, 832, 384))
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(1269, 684, 395, 73))
        
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        Form.gridLayout.addWidget(self.frame,2,1,1,1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        time = sqlCourseData[4].strftime("%H:%M:%S")
        materialList = ""
        for i in sqlMaterialData:
            materialList = materialList+i+"<br />"
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\" font-family:\'Inter\'; font-size:64px; font-weight:696; color:#000000; vertical-align:middle;\">"
""+sqlCourseData[0]+"<br />"+sqlCourseData[1]+"<br /></span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form","<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\"font-family:\'Inter\'; font-size:28px; font-weight:696; color:#000000;\">"
""+sqlCourseData[2]+"<br />"+sqlCourseData[3]+"<br />"+time+"<br />"+sqlCourseData[5]+"<br /></span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<html><head/>\n"
"<body>\n<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
"<span style=\"font-family:\'Inter\'; font-size:28px; font-weight:696; color:#000000;\">"
""+materialList+"</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Send to Email"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = CourseInfo()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
