# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login import MainWindow
from welcomeMsg import WelMsg
from course_info import CourseInfo
from menuBar import MenuBar
from sidebar import Sidebar

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint) 
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1920, 1080)
        self.setStyleSheet("background-color: #ffffff")
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.HLayoutWidget = QtWidgets.QWidget(self)
        self.HLayoutWidget.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.HLayoutWidget.setObjectName("HLayoutWidget")
        self.HLayout = QtWidgets.QHBoxLayout(self.HLayoutWidget)
        self.HLayout.setContentsMargins(0, 0, 0, 0)
        self.HLayout.setObjectName("HLayout")
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
    
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uiMainWindow = Ui_MainWindow()
    # Login stuff 
    Login = MainWindow()
    Login.setupUi(uiMainWindow)
        
    uiMainWindow.show()
    sys.exit(app.exec_())
